name: CI Build & Push

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write   # 💡 必须加这行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        env:
          IMAGE: ghcr.io/${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          IMAGE_LC=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_LC:latest -t $IMAGE_LC:$SHA .
          docker push $IMAGE_LC:latest
          docker push $IMAGE_LC:$SHA
